import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import '@/styles/command.css';
import NextAuthSessionProvider from "@/lib/providers/SessionProvider";
import LayoutTest from './layout-test';
import { CartProvider } from '@/contexts/CartContext';
import { Toaster } from "@/components/ui/toaster";
import { ToastProvider } from "@/components/ui/toast";

// Using widely available Google Fonts since @vercel/font-geist isn't available
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // The root layout should not have the RouteGuard
  // We'll apply it selectively to protected routes instead
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <ToastProvider>
          <body className={`${inter.variable} ${robotoMono.variable}`}>
            <CartProvider>
              {children}
            </CartProvider>
            <Toaster />
          </body>
        </ToastProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
